name: Beta Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm i

      - name: Build
        run: npm run build

      - name: Create release branch and bump version
        run: sed -i "s/    'version' => 'development',/    'version' => 'beta',/" config/app.php

      - name: Add commit sha to app.php
        run: sed -i "s/    'commit' => '',/    'commit' => '${{ github.sha }}',/" config/app.php

      - name: Create beta archive
        run: | 
            rm -rf node_modules vendor tests CODE_OF_CONDUCT.md CONTRIBUTING.md flake.lock flake.nix phpstan.neon phpunit.xml shell.nix
            tar -czf paymenter.tar.gz * .env.example .gitignore

      # Add to action file
      # - name: Upload archive to https://api.paymenter.org/beta
        # uses: JantHsueh/upload-file-action@master
        # with:
          # url: https://api.paymenter.org/beta
          # forms: '{"api_key": "${{ secrets.API_KEY }}"}'
          # fileForms: '{"file": "paymenter.tar.gz"}'

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: beta-${{ github.sha }}
          release_name: Beta Release ${{ github.sha }}
          draft: false
          prerelease: true
  
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./paymenter.tar.gz
          asset_name: paymenter.tar.gz
          asset_content_type: application/gzip